recipe: default.v1
language: en
pipeline:
  - name: scripts.cmd_generator.CustomCommandGenerator
    prompt_template: ./cmd_generator_2.md.jinja2
    llm:
      model_group: proxy_cmd_generator
#      model_group: cmd_generator_finetuned
    flow_retrieval:
      active: false

policies:
  - name: FlowPolicy

  # Decided not to use it, because it does not give enough flexibility.
  #  - name: EnterpriseSearchPolicy
  #    vector_store:
  #      type: "scripts.ee_faq.EEFAQ"
  #      embeddings:
  #        provider: "openai"
  #        model: "text-embedding-3-small"




assistant_id: 20250318-131727-tense-dessert
