recipe: default.v1
language: en
pipeline:
  #  - name: NLUCommandAdapter
#  - name: CompactLLMCommandGenerator
  - name: scripts.cmd_generator.CustomCommandGenerator
    prompt_template: ./cmd_generator_2.md.jinja2
    llm:
      model_group: proxy_cmd_generator
    flow_retrieval:
      active: false

policies:
  - name: FlowPolicy
  #  - name: IntentlessPolicy
  #  - name: RulePolicy
  #    core_fallback_threshold: 0.3
  #    enable_fallback_prediction: true
  #    core_fallback_action_name: action_default_fallback

  # Decided not to use it, because it does not give enough flexibility.
  #  - name: EnterpriseSearchPolicy
  #    vector_store:
  #      type: "scripts.ee_faq.EEFAQ"
  #      embeddings:
  #        provider: "openai"
  #        model: "text-embedding-3-small"




assistant_id: 20250318-131727-tense-dessert
